/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Mesto;
import domen.Otkupljivac;
import domen.Sorta;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Bojana
 */
public class DodajPriznanicuForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajPriznanicuForma
     */
    public DodajPriznanicuForma() {
        initComponents();
    }

    public JTable getTblProizvodjaci() {
        return tblProizvodjaci;
    }

    public void setTblProizvodjaci(JTable tblProizvodjaci) {
        this.tblProizvodjaci = tblProizvodjaci;
    }

    public JTable getTblStavkePriznanice() {
        return tblStavkePriznanice;
    }

    public void setTblStavkePriznanice(JTable tblStavkePriznanice) {
        this.tblStavkePriznanice = tblStavkePriznanice;
    }

    public JTextField getTxtDatumIzdavanja() {
        return txtDatumIzdavanja;
    }

    public void setTxtDatumIzdavanja(JTextField txtDatumIzdavanja) {
        this.txtDatumIzdavanja = txtDatumIzdavanja;
    }

    public JTextField getTxtIdPriznanice() {
        return txtIdPriznanice;
    }

    public void setTxtIdPriznanice(JTextField txtIdPriznanice) {
        this.txtIdPriznanice = txtIdPriznanice;
    }

    public JTextField getTxtImeProizvodjaca() {
        return txtImeProizvodjaca;
    }

    public void setTxtImeProizvodjaca(JTextField txtImeProizvodjaca) {
        this.txtImeProizvodjaca = txtImeProizvodjaca;
    }

    public JTextField getTxtPrezimeProizvodjaca() {
        return txtPrezimeProizvodjaca;
    }

    public void setTxtPrezimeProizvodjaca(JTextField txtPrezimeProizvodjaca) {
        this.txtPrezimeProizvodjaca = txtPrezimeProizvodjaca;
    }

    public JComboBox<Mesto> getCmbMesto() {
        return cmbMesto;
    }

    public void setCmbMesto(JComboBox<Mesto> cmbMesto) {
        this.cmbMesto = cmbMesto;
    }

    public JTextField getTxtIzabraniProizvodjac() {
        return txtIzabraniProizvodjac;
    }

    public void setTxtIzabraniProizvodjac(JTextField txtIzabraniProizvodjac) {
        this.txtIzabraniProizvodjac = txtIzabraniProizvodjac;
    }

    public JComboBox<Sorta> getCmbSorte() {
        return cmbSorte;
    }

    public void setCmbSorte(JComboBox<Sorta> cmbSorte) {
        this.cmbSorte = cmbSorte;
    }

    public JTextField getTxtJM() {
        return txtJM;
    }

    public void setTxtJM(JTextField txtJM) {
        this.txtJM = txtJM;
    }

    public JTextField getTxtKolicina() {
        return txtKolicina;
    }

    public void setTxtKolicina(JTextField txtKolicina) {
        this.txtKolicina = txtKolicina;
    }

    public JTextField getTxtUkupnaVrednost() {
        return txtUkupnaVrednost;
    }

    public void setTxtUkupnaVrednost(JTextField txtUkupnaVrednost) {
        this.txtUkupnaVrednost = txtUkupnaVrednost;
    }

    public JComboBox<Otkupljivac> getCmbOtkupljivaci() {
        return cmbOtkupljivaci;
    }

    public void setCmbOtkupljivaci(JComboBox<Otkupljivac> cmbOtkupljivaci) {
        this.cmbOtkupljivaci = cmbOtkupljivaci;
    }

    public JButton getBtnAzurirajPriznanicu() {
        return btnAzurirajPriznanicu;
    }

    public void setBtnAzurirajPriznanicu(JButton btnAzurirajPriznanicu) {
        this.btnAzurirajPriznanicu = btnAzurirajPriznanicu;
    }

    public JButton getBtnSacuvajPriznanicu() {
        return btnSacuvajPriznanicu;
    }

    public void setBtnSacuvajPriznanicu(JButton btnSacuvajPriznanicu) {
        this.btnSacuvajPriznanicu = btnSacuvajPriznanicu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtIdPriznanice = new javax.swing.JTextField();
        lblId1 = new javax.swing.JLabel();
        txtDatumIzdavanja = new javax.swing.JTextField();
        lblId2 = new javax.swing.JLabel();
        pnlProizvodjac = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtImeProizvodjaca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrezimeProizvodjaca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbMesto = new javax.swing.JComboBox<>();
        pnlNadjeniProizvodjaci = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProizvodjaci = new javax.swing.JTable();
        btnIzaberiProizvodjaca = new javax.swing.JButton();
        btnPretraziProizvodjace = new javax.swing.JButton();
        btnResetujPretragu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkePriznanice = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtJM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbSorte = new javax.swing.JComboBox<>();
        btnObrisiStavku = new javax.swing.JButton();
        lblProizvodjac = new javax.swing.JLabel();
        txtIzabraniProizvodjac = new javax.swing.JTextField();
        cmbOtkupljivaci = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtUkupnaVrednost = new javax.swing.JTextField();
        btnAzurirajPriznanicu = new javax.swing.JButton();
        btnSacuvajPriznanicu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kreiranje nove priznanice");

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId.setText("ID:");

        txtIdPriznanice.setEnabled(false);

        lblId1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId1.setText("Datum izdavanja:");

        lblId2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId2.setText("Otkupljivač:");

        pnlProizvodjac.setBorder(javax.swing.BorderFactory.createTitledBorder("Proizvođač"));

        jLabel4.setText("Ime:");

        jLabel5.setText("Prezime:");

        jLabel6.setText("Mesto:");

        tblProizvodjaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProizvodjaci);

        btnIzaberiProizvodjaca.setText("Izaberi proizvođača");

        javax.swing.GroupLayout pnlNadjeniProizvodjaciLayout = new javax.swing.GroupLayout(pnlNadjeniProizvodjaci);
        pnlNadjeniProizvodjaci.setLayout(pnlNadjeniProizvodjaciLayout);
        pnlNadjeniProizvodjaciLayout.setHorizontalGroup(
            pnlNadjeniProizvodjaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNadjeniProizvodjaciLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlNadjeniProizvodjaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNadjeniProizvodjaciLayout.createSequentialGroup()
                        .addComponent(btnIzaberiProizvodjaca)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNadjeniProizvodjaciLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlNadjeniProizvodjaciLayout.setVerticalGroup(
            pnlNadjeniProizvodjaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNadjeniProizvodjaciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnIzaberiProizvodjaca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPretraziProizvodjace.setText("Pretraži");

        btnResetujPretragu.setText("Resetuj pretragu");

        javax.swing.GroupLayout pnlProizvodjacLayout = new javax.swing.GroupLayout(pnlProizvodjac);
        pnlProizvodjac.setLayout(pnlProizvodjacLayout);
        pnlProizvodjacLayout.setHorizontalGroup(
            pnlProizvodjacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProizvodjacLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlProizvodjacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProizvodjacLayout.createSequentialGroup()
                        .addGroup(pnlProizvodjacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProizvodjacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrezimeProizvodjaca)
                            .addComponent(txtImeProizvodjaca)
                            .addComponent(cmbMesto, 0, 170, Short.MAX_VALUE)
                            .addComponent(btnPretraziProizvodjace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlProizvodjacLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnResetujPretragu)))
                .addGap(28, 28, 28)
                .addComponent(pnlNadjeniProizvodjaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnlProizvodjacLayout.setVerticalGroup(
            pnlProizvodjacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProizvodjacLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlProizvodjacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNadjeniProizvodjaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlProizvodjacLayout.createSequentialGroup()
                        .addGroup(pnlProizvodjacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtImeProizvodjaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pnlProizvodjacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrezimeProizvodjaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pnlProizvodjacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnPretraziProizvodjace)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetujPretragu)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stavke priznanice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tblStavkePriznanice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkePriznanice);

        btnDodajStavku.setText("Dodaj stavku");

        jLabel1.setText("Jedinica mere:");

        jLabel2.setText("Količina:");

        jLabel3.setText("Sorta:");

        btnObrisiStavku.setText("Obriši stavku");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJM)
                            .addComponent(txtKolicina)
                            .addComponent(cmbSorte, 0, 159, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDodajStavku, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(btnObrisiStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtJM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbSorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiStavku)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        lblProizvodjac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProizvodjac.setText("Proizvođač:");

        txtIzabraniProizvodjac.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblId1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDatumIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtIdPriznanice, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblId2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbOtkupljivaci, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIzabraniProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlProizvodjac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdPriznanice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatumIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId2)
                    .addComponent(cmbOtkupljivaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProizvodjac)
                    .addComponent(txtIzabraniProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(pnlProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Ukupna vrednost:");

        txtUkupnaVrednost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUkupnaVrednost.setEnabled(false);

        btnAzurirajPriznanicu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAzurirajPriznanicu.setText("Ažuriraj priznanicu");

        btnSacuvajPriznanicu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSacuvajPriznanicu.setText("Sačuvaj priznanicu");
        btnSacuvajPriznanicu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUkupnaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(btnSacuvajPriznanicu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAzurirajPriznanicu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtUkupnaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAzurirajPriznanicu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSacuvajPriznanicu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzurirajPriznanicu;
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzaberiProizvodjaca;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnPretraziProizvodjace;
    private javax.swing.JButton btnResetujPretragu;
    private javax.swing.JButton btnSacuvajPriznanicu;
    private javax.swing.JComboBox<Mesto> cmbMesto;
    private javax.swing.JComboBox<Otkupljivac> cmbOtkupljivaci;
    private javax.swing.JComboBox<Sorta> cmbSorte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblId2;
    private javax.swing.JLabel lblProizvodjac;
    private javax.swing.JPanel pnlNadjeniProizvodjaci;
    private javax.swing.JPanel pnlProizvodjac;
    private javax.swing.JTable tblProizvodjaci;
    private javax.swing.JTable tblStavkePriznanice;
    private javax.swing.JTextField txtDatumIzdavanja;
    private javax.swing.JTextField txtIdPriznanice;
    private javax.swing.JTextField txtImeProizvodjaca;
    private javax.swing.JTextField txtIzabraniProizvodjac;
    private javax.swing.JTextField txtJM;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtPrezimeProizvodjaca;
    private javax.swing.JTextField txtUkupnaVrednost;
    // End of variables declaration//GEN-END:variables

    public void SacuvajPriznanicuAddActionListener(ActionListener actionListener) {
        btnSacuvajPriznanicu.addActionListener(actionListener);
    }

    public void addBtnResetujPretraguActionListener(ActionListener actionListener) {
        btnResetujPretragu.addActionListener(actionListener);
    }

    public void addBtnPretraziActionListener(ActionListener actionListener) {
        btnPretraziProizvodjace.addActionListener(actionListener);
    }

    public void addBtnIzaberiProizvodjacaActionListener(ActionListener actionListener) {
        btnIzaberiProizvodjaca.addActionListener(actionListener);
    }

    public void addBtnDodajStavkuActionListener(ActionListener actionListener) {
        btnDodajStavku.addActionListener(actionListener);
    }

    public void addBtnObrisiStavkuActionListener(ActionListener actionListener) {
        btnObrisiStavku.addActionListener(actionListener);
    }

    public void addBtnAzurirajPriznanicuActionListener(ActionListener actionListener) {
        btnAzurirajPriznanicu.addActionListener(actionListener);
    }

   
}
